version: "3"
services:
  api:
    image: amb_server:latest
    build:
      dockerfile: ./API/Dockerfile
    ports:
      - "8030:8080"
    networks:
      - backend

  mysql:
    image: mysql:latest
    restart: always
    container_name: mysql_ambulancey
    ports:
      - "3222:3306"
    environment:
      - MYSQL_DATABASE:ambulancey
      - MYSQL_ROOT_PASSWORD=1234
      - TZ = Asia/Seoul
      - C:\Users\user\Desktop\Back\docker\ambulancey:/var/lib/mysql
    networks:
      - backend
networks:
  backend:
    driver: bridge