
  spring:
    datasource:
      url: jdbc:mysql://localhost:3222/ambulancey
      username: root
      password: 1234
      driver-class-name: com.mysql.cj.jdbc.Driver


#jwt:
#  prefix: ${JWT_PROFIX:Bearer}
#  header: ${JWT_HEADER:Authorization}
#  secret: ${JWT_SECRET:whsrudgksmsrnralssddufjqns}
#  expiration_access: ${1000*60*10}
#  #expiration_refresh: ${1000*60*60*48}

