name: CICD
#
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: "adopt"

      - name: Build with Gradle
        run: |
          chmod +x ./gradlew
          ./gradlew clean build -x test

      - name: Docker build & push docker repo
        run: |
          docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
          docker build -f ./API/Dockerfile -t ${{ secrets.DOCKER_REPO }}/dev .
          docker push ${{ secrets.DOCKER_REPO }}/dev

      - name: Create application_aws.yml from secret
        run: |
            echo "${{ secrets.APPLICATION_AWS }}" > ./API/src/main/resources/application-aws.yml
            cat ./path/to/your/application_aws.yml  # Ensure the content is written

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        id: deploy
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          envs: GITHUB_SHA
          script: |
            cd ambulancey-docker-com
            docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
            sudo docker pull ${{ secrets.DOCKER_REPO }}/dev
            sudo docker compose up --build -d
            sudo docker image prune -f
  

    

